import { Worker, type Job } from "bullmq"
import IORedis from "ioredis"
import { createWorkerConnection } from "../lib/redis.js"
import { config } from "../lib/config.js"
import { forTenant } from "@techteam/database"
import type { AgentJobData, AgentJobResult } from "./agent.queue.js"
import { publishWsEvent } from "../lib/ws-events.js"
import type { WsEvent } from "@techteam/shared"

// Fire-and-forget wrapper: ensures publishWsEvent failures never block or crash the worker.
// publishWsEvent already has try/catch internally, but this provides double safety.
async function emitEvent(event: WsEvent): Promise<void> {
  try { await publishWsEvent(event) } catch { /* never block worker */ }
}

// Reusable Redis client for concurrency operations (dev slot semaphore)
let concurrencyRedis: IORedis | null = null
function getConcurrencyRedis(): IORedis {
  if (!concurrencyRedis) {
    concurrencyRedis = new IORedis(config.REDIS_URL)
  }
  return concurrencyRedis
}

// Timeout per phase (AGENT-07 requirement)
const PHASE_TIMEOUTS: Record<string, number> = {
  discovery: 2 * 60 * 1000, // 2 minutes
  planning: 5 * 60 * 1000, // 5 minutes
  development: 30 * 60 * 1000, // 30 minutes
  testing: 10 * 60 * 1000, // 10 minutes
}

// Maximum rejection cycles before pausing for human review
const MAX_REJECTION_CYCLES = 3

/**
 * Builds a markdown PR body from the demand and development agent output.
 */
function buildPrBody(
  demand: { plan: unknown; requirements: unknown },
  devOutput: { approach?: string; filesChanged?: string[] } | null
): string {
  const plan = demand.plan as { tasks?: { title: string }[] } | null
  const reqs = demand.requirements as {
    functionalRequirements?: { description: string }[]
  } | null

  const sections: string[] = []

  sections.push(`## Summary`)
  sections.push(
    devOutput?.approach ??
      "Automated implementation by TechTeam Development Agent"
  )

  sections.push(`## Plan Tasks`)
  sections.push(
    plan?.tasks?.map((t) => `- ${t.title}`).join("\n") ?? "See demand plan"
  )

  sections.push(`## Requirements`)
  sections.push(
    reqs?.functionalRequirements?.map((r) => `- ${r.description}`).join("\n") ??
      "See demand requirements"
  )

  sections.push(`## Files Changed`)
  sections.push(
    devOutput?.filesChanged?.map((f) => `- ${f}`).join("\n") ?? "See PR diff"
  )

  sections.push(`---`)
  sections.push(`_Generated by TechTeam Development Agent_`)

  return sections.join("\n\n")
}

/**
 * Creates and returns the BullMQ worker for the agent pipeline.
 * The worker processes agent jobs with tenant isolation, retry handling,
 * and automatic stage advancement.
 */
export function createAgentWorker() {
  const worker = new Worker<AgentJobData, AgentJobResult>(
    "agent-pipeline",
    async (job: Job<AgentJobData>) => {
      const { demandId, tenantId, projectId, phase } = job.data
      const attempt = job.attemptsMade + 1

      console.log(
        `[agent-worker] Processing job ${job.id}: phase=${phase}, demandId=${demandId}, attempt=${attempt}`
      )

      const prisma = forTenant(tenantId)

      // Create AgentRun record with status 'running'
      const agentRun = await prisma.agentRun.create({
        data: {
          demandId,
          phase,
          status: "running",
          attempt,
        } as any,
      })
      await emitEvent({ type: "agent-run:updated", tenantId, payload: { demandId } })

      try {
        // Dynamically import the correct agent function based on phase
        // Lazy import avoids circular dependencies
        let agentResult: {
          output: unknown
          hasAmbiguities?: boolean
          approved?: boolean
          tokensIn: number
          tokensOut: number
          costUsd: number
          durationMs: number
        }

        if (phase === "discovery") {
          const { runDiscoveryAgent } = await import(
            "../agents/discovery.agent.js"
          )
          agentResult = await runDiscoveryAgent({
            demandId,
            tenantId,
            projectId,
            timeout: PHASE_TIMEOUTS[phase]!,
          })
        } else if (phase === "planning") {
          const { runPlanningAgent } = await import(
            "../agents/planning.agent.js"
          )
          agentResult = await runPlanningAgent({
            demandId,
            tenantId,
            projectId,
            timeout: PHASE_TIMEOUTS[phase]!,
          })
        } else if (phase === "development") {
          await handleDevelopmentPhase({
            demandId,
            tenantId,
            projectId,
            phase,
            prisma,
            agentRun,
          })
          // Development handler manages its own stage advancement and metrics
          // Return a minimal result -- the handler already updated everything
          return { output: null, tokensIn: 0, tokensOut: 0, costUsd: 0, durationMs: 0 }
        } else if (phase === "testing") {
          await handleTestingPhase({
            demandId,
            tenantId,
            projectId,
            phase,
            prisma,
            agentRun,
          })
          return { output: null, tokensIn: 0, tokensOut: 0, costUsd: 0, durationMs: 0 }
        } else {
          throw new Error(`Unknown phase: ${phase}`)
        }

        // Update AgentRun to completed with token/cost metrics
        await prisma.agentRun.update({
          where: { id: agentRun.id },
          data: {
            status: "completed",
            output: agentResult.output as any,
            tokensIn: agentResult.tokensIn,
            tokensOut: agentResult.tokensOut,
            costUsd: agentResult.costUsd,
            durationMs: agentResult.durationMs,
          },
        })
        await emitEvent({ type: "agent-run:updated", tenantId, payload: { demandId } })

        // Update demand agentStatus and accumulate token/cost totals
        await prisma.demand.update({
          where: { id: demandId },
          data: {
            agentStatus: null,
            totalTokens: {
              increment: agentResult.tokensIn + agentResult.tokensOut,
            },
            totalCostUsd: { increment: agentResult.costUsd },
          },
        })
        await emitEvent({ type: "agent:status-changed", tenantId, payload: { demandId, projectId } })

        // Handle stage advancement and store agent output on demand
        if (phase === "discovery") {
          // Store discovery requirements and complexity on demand
          const discoveryOutput = agentResult.output as {
            complexity?: string
          }
          await prisma.demand.update({
            where: { id: demandId },
            data: {
              requirements: agentResult.output as any,
              complexity: (discoveryOutput.complexity as any) ?? null,
            },
          })
          await emitEvent({ type: "demand:updated", tenantId, payload: { demandId, projectId } })

          if (agentResult.hasAmbiguities) {
            // Keep in discovery, set paused for human clarification
            await prisma.demand.update({
              where: { id: demandId },
              data: { agentStatus: "paused" },
            })
            await emitEvent({ type: "agent:status-changed", tenantId, payload: { demandId, projectId } })
          } else {
            // Advance to planning and enqueue planning job
            await prisma.demand.update({
              where: { id: demandId },
              data: { stage: "planning", agentStatus: "queued" },
            })
            await emitEvent({ type: "demand:stage-changed", tenantId, payload: { demandId, projectId } })
            const { agentQueue } = await import("./agent.queue.js")
            await agentQueue.add("run-agent", {
              demandId,
              tenantId,
              projectId,
              phase: "planning",
            })
          }
        } else if (phase === "planning") {
          // Store plan on demand, advance to development, and auto-enqueue development job
          await prisma.demand.update({
            where: { id: demandId },
            data: {
              plan: agentResult.output as any,
              stage: "development",
              agentStatus: "queued",
            },
          })
          await emitEvent({ type: "demand:stage-changed", tenantId, payload: { demandId, projectId } })
          await emitEvent({ type: "demand:updated", tenantId, payload: { demandId, projectId } })
          const { agentQueue } = await import("./agent.queue.js")
          await agentQueue.add("run-agent", {
            demandId,
            tenantId,
            projectId,
            phase: "development",
          })
        }

        console.log(
          `[agent-worker] Job ${job.id} completed: phase=${phase}, demandId=${demandId}`
        )

        return agentResult as AgentJobResult
      } catch (error: unknown) {
        const errorMessage =
          error instanceof Error ? error.message : String(error)
        const isTimeout = errorMessage.includes("timed out")

        // Update AgentRun to failed/timeout
        await prisma.agentRun.update({
          where: { id: agentRun.id },
          data: {
            status: isTimeout ? "timeout" : "failed",
            error: errorMessage,
          },
        })
        await emitEvent({ type: "agent-run:updated", tenantId, payload: { demandId } })

        // Set demand agentStatus to failed
        await prisma.demand.update({
          where: { id: demandId },
          data: { agentStatus: "failed" },
        })
        await emitEvent({ type: "agent:status-changed", tenantId, payload: { demandId, projectId } })

        // NOTIF-01: Notify on agent failure
        try {
          const failedDemand = await prisma.demand.findUnique({
            where: { id: demandId },
            select: { title: true, projectId: true },
          })
          if (failedDemand) {
            await (prisma as any).notification.create({
              data: {
                type: "agent_failed",
                title: `Agent failed: ${phase}`,
                message: `Agent failed for "${failedDemand.title}" during ${phase} phase. Error: ${errorMessage.slice(0, 200)}`,
                demandId,
                projectId: failedDemand.projectId,
              },
            })
            await emitEvent({ type: "notification:created", tenantId, payload: { demandId } })
          }
        } catch (notifErr) {
          // Never let notification creation mask the original error (research pitfall 4)
          console.warn("[agent-worker] Failed to create notification:", notifErr)
        }

        console.error(
          `[agent-worker] Job ${job.id} failed: ${errorMessage}`
        )

        // Re-throw so BullMQ handles retry
        throw error
      }
    },
    {
      connection: createWorkerConnection(),
      concurrency: 2,
    }
  )

  // CRITICAL: Always attach error handler per BullMQ docs
  worker.on("error", (err) => {
    console.error("[agent-worker] Worker error:", err)
  })

  return worker
}

/**
 * Handles the development phase: validate repo, branch, invoke dev agent,
 * commit, push, create PR, advance to testing.
 *
 * CONC-01/CONC-02: Development phase requires dev slot gating.
 * Discovery and Planning (CONC-03) run freely in parallel -- no slot needed.
 */
async function handleDevelopmentPhase(ctx: {
  demandId: string
  tenantId: string
  projectId: string
  phase: string
  prisma: ReturnType<typeof forTenant>
  agentRun: { id: string }
}) {
  const { demandId, tenantId, projectId, phase, prisma, agentRun } = ctx

  // --- Concurrency gating ---
  const { acquireDevSlot, releaseDevSlot } = await import("../lib/concurrency.js")
  const redis = getConcurrencyRedis()

  // Fetch demand and project early (project needed for maxConcurrentDev slot check)
  const demand = await prisma.demand.findUniqueOrThrow({
    where: { id: demandId },
  })
  const project = await prisma.project.findUniqueOrThrow({
    where: { id: projectId },
  })

  const acquired = await acquireDevSlot(
    redis, projectId, demandId, project.maxConcurrentDev
  )

  if (!acquired) {
    // No available dev slot -- re-enqueue with delay
    const { agentQueue } = await import("./agent.queue.js")
    await agentQueue.add("run-agent", {
      demandId,
      tenantId,
      projectId,
      phase: "development",
    }, {
      delay: 30_000, // 30 seconds
      jobId: `dev-retry-${demandId}-${Date.now()}`,
    })

    // Update demand to show it's waiting
    await prisma.demand.update({
      where: { id: demandId },
      data: { agentStatus: "queued" },
    })
    await emitEvent({ type: "agent:status-changed", tenantId, payload: { demandId, projectId } })

    // Delete the AgentRun we just created (it's not a real run)
    await prisma.agentRun.delete({
      where: { id: agentRun.id },
    })

    console.log(
      `[agent-worker] Dev slot full for project ${projectId}: demandId=${demandId}, re-enqueuing with 30s delay`
    )
    return
  }

  // --- Dev slot acquired, proceed with development ---
  try {
    // Dynamic imports (same pattern as discovery/planning)
    const { runDevelopmentAgent } = await import(
      "../agents/development.agent.js"
    )
    const {
      createIsolatedBranch,
      commitAndPush,
      resetWorkingDir,
      validateGitRepo,
      createGitClient,
      getWorktreePath,
      createWorktree,
    } = await import("../lib/git.js")
    const { createPullRequest, getGithubTokenForTenant } = await import("../lib/github.js")

    // Fetch tenant's GitHub token for push and PR operations
    const githubToken = await getGithubTokenForTenant(tenantId)

    // 1. Validate repoPath exists and is a git repo
    const isValid = await validateGitRepo(project.repoPath)
    if (!isValid) {
      throw new Error(
        "Project repoPath does not exist or is not a git repository"
      )
    }

    // 2. Branch and worktree management
    let branchName = demand.branchName as string | null
    let effectiveRepoPath = project.repoPath
    let usingWorktree = false

    // Use worktree when maxConcurrentDev > 1 to isolate concurrent development
    if (project.maxConcurrentDev > 1) {
      const worktreePath = getWorktreePath(project.repoPath, demandId)
      if (!branchName) {
        // First run: create worktree with new branch
        const slug = demand.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 50)
        branchName = `demand/${demand.id}-${slug}`
        await createWorktree(project.repoPath, worktreePath, branchName, project.defaultBranch)
        await prisma.demand.update({
          where: { id: demandId },
          data: { branchName },
        })
      }
      // NOTE: For rejection re-entry with worktree, the worktree should already exist.
      // If it doesn't (e.g., cleaned up), recreate it.
      effectiveRepoPath = worktreePath
      usingWorktree = true
    } else {
      // Single-dev mode: use standard branch management on main repo
      if (!branchName) {
        // First run: create isolated branch
        const slug = demand.title
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, "-")
          .slice(0, 50)
        branchName = `demand/${demand.id}-${slug}`
        await createIsolatedBranch(project.repoPath, branchName, project.defaultBranch)
        await prisma.demand.update({
          where: { id: demandId },
          data: { branchName },
        })
      } else {
        // Rejection re-entry: checkout existing branch
        const git = createGitClient(project.repoPath)
        await git.checkout(branchName)
      }
    }

    try {
      // 3. Invoke development agent
      const agentResult = await runDevelopmentAgent({
        demandId,
        tenantId,
        projectId,
        timeout: PHASE_TIMEOUTS[phase]!,
        rejectionFeedback: (demand.testingFeedback as unknown) ?? undefined,
      })

      // Update AgentRun to completed
      await prisma.agentRun.update({
        where: { id: agentRun.id },
        data: {
          status: "completed",
          output: agentResult.output as any,
          tokensIn: agentResult.tokensIn,
          tokensOut: agentResult.tokensOut,
          costUsd: agentResult.costUsd,
          durationMs: agentResult.durationMs,
        },
      })
      await emitEvent({ type: "agent-run:updated", tenantId, payload: { demandId } })

      // Accumulate token/cost totals
      await prisma.demand.update({
        where: { id: demandId },
        data: {
          totalTokens: {
            increment: agentResult.tokensIn + agentResult.tokensOut,
          },
          totalCostUsd: { increment: agentResult.costUsd },
        },
      })

      // 4. Commit and push (use effectiveRepoPath for worktree support)
      const commitMessage =
        agentResult.output?.commitMessage ??
        `feat(demand/${demand.id}): ${demand.title}`
      await commitAndPush(effectiveRepoPath, branchName, commitMessage)

      // 5. PR management
      const prUrl = demand.prUrl as string | null
      if (!prUrl) {
        // First run: create PR
        const newPrUrl = await createPullRequest({
          repoUrl: project.repoUrl,
          title: `[Demand ${demand.id}] ${demand.title}`,
          body: buildPrBody(demand, agentResult.output),
          head: branchName,
          base: project.defaultBranch,
          token: githubToken,
        })
        await prisma.demand.update({
          where: { id: demandId },
          data: { prUrl: newPrUrl },
        })
      }
      // If prUrl exists, the push already updates the existing PR

      // 6. Advance to testing
      await prisma.demand.update({
        where: { id: demandId },
        data: { stage: "testing", agentStatus: "queued" },
      })
      await emitEvent({ type: "demand:stage-changed", tenantId, payload: { demandId, projectId } })
      const { agentQueue } = await import("./agent.queue.js")
      await agentQueue.add("run-agent", {
        demandId,
        tenantId,
        projectId,
        phase: "testing",
      })

      // NOTE: Worktree is NOT cleaned up here -- it persists through testing phase
      // and is cleaned up by the merge worker after merge completes

      console.log(
        `[agent-worker] Development completed: demandId=${demandId}, branch=${branchName}`
      )
    } catch (error: unknown) {
      // Error handling: clean up dirty files on development failure
      await resetWorkingDir(effectiveRepoPath)
      throw error
    }
  } finally {
    await releaseDevSlot(redis, projectId, demandId)
    console.log(`[agent-worker] Dev slot released: project=${projectId}, demand=${demandId}`)
  }
}

/**
 * Handles the testing phase: invoke testing agent, approve or reject
 * with feedback loop (max 3 rejection cycles).
 */
async function handleTestingPhase(ctx: {
  demandId: string
  tenantId: string
  projectId: string
  phase: string
  prisma: ReturnType<typeof forTenant>
  agentRun: { id: string }
}) {
  const { demandId, tenantId, projectId, phase, prisma, agentRun } = ctx

  // Dynamic imports
  const { runTestingAgent } = await import("../agents/testing.agent.js")
  const { createGitClient } = await import("../lib/git.js")

  // 1. Fetch demand and project
  const demand = await prisma.demand.findUniqueOrThrow({
    where: { id: demandId },
  })
  const project = await prisma.project.findUniqueOrThrow({
    where: { id: projectId },
  })

  // 2. Checkout demand branch
  const branchName = demand.branchName as string
  if (!branchName) {
    throw new Error(
      "Cannot run testing without a branch. " +
        "Ensure development phase completed successfully before running testing."
    )
  }
  const git = createGitClient(project.repoPath)
  await git.checkout(branchName)

  // 3. Invoke testing agent
  const testResult = await runTestingAgent({
    demandId,
    tenantId,
    projectId,
    timeout: PHASE_TIMEOUTS[phase]!,
  })

  // Update AgentRun to completed
  await prisma.agentRun.update({
    where: { id: agentRun.id },
    data: {
      status: "completed",
      output: testResult.output as any,
      tokensIn: testResult.tokensIn,
      tokensOut: testResult.tokensOut,
      costUsd: testResult.costUsd,
      durationMs: testResult.durationMs,
    },
  })
  await emitEvent({ type: "agent-run:updated", tenantId, payload: { demandId } })

  // Accumulate token/cost totals
  await prisma.demand.update({
    where: { id: demandId },
    data: {
      totalTokens: {
        increment: testResult.tokensIn + testResult.tokensOut,
      },
      totalCostUsd: { increment: testResult.costUsd },
    },
  })

  // 4/5. Handle verdict
  if (testResult.approved) {
    // Approved: advance to merge and enqueue merge job
    await prisma.demand.update({
      where: { id: demandId },
      data: { stage: "merge", agentStatus: "queued" },
    })
    await emitEvent({ type: "demand:stage-changed", tenantId, payload: { demandId, projectId } })
    const { mergeQueue } = await import("./merge.queue.js")
    await mergeQueue.add("merge-demand", {
      demandId,
      tenantId,
      projectId,
    })
    console.log(
      `[agent-worker] Testing approved: demandId=${demandId}, enqueuing merge job`
    )
  } else {
    // Rejected: increment rejection count and check threshold
    const newRejectionCount = ((demand.rejectionCount as number) ?? 0) + 1

    if (newRejectionCount >= MAX_REJECTION_CYCLES) {
      // Too many rejections: pause for human review
      await prisma.demand.update({
        where: { id: demandId },
        data: {
          agentStatus: "paused",
          rejectionCount: newRejectionCount,
          testingFeedback: testResult.output as any,
        },
      })
      await emitEvent({ type: "agent:status-changed", tenantId, payload: { demandId, projectId } })
      console.log(
        `[agent-worker] Demand paused after ${MAX_REJECTION_CYCLES} rejection cycles: demandId=${demandId}`
      )
    } else {
      // Return to development with feedback
      await prisma.demand.update({
        where: { id: demandId },
        data: {
          stage: "development",
          agentStatus: "queued",
          rejectionCount: newRejectionCount,
          testingFeedback: testResult.output as any,
        },
      })
      await emitEvent({ type: "demand:stage-changed", tenantId, payload: { demandId, projectId } })
      const { agentQueue } = await import("./agent.queue.js")
      await agentQueue.add("run-agent", {
        demandId,
        tenantId,
        projectId,
        phase: "development",
      })
      console.log(
        `[agent-worker] Testing rejected (${newRejectionCount}/${MAX_REJECTION_CYCLES}): demandId=${demandId}, returning to development`
      )
    }
  }
}
